	SELECT *
	FROM SDATADB.OC_C_CUST_RELA_01 A
	LEFT JOIN SDATADB.OC_C_CUST_NATURAL_01 B
		ON A.CUST_NO(CS) = B.PERSON_ID(CS)
	LEFT JOIN PDATADB.T98_CODE_REF C
		ON C.SRC_SYSTEM_NAME = 'OC'
	WHERE A.RELA_CUST_TYPE = '1'
		AND A.RELATIONSHIP_TYPE <> ''
		AND A.RELA_CUST_NO <> '' 
	QUALIFY ROW_NUMBER() OVER (
			PARTITION BY A.RELA_CUST_NO
			,A.RELATIONSHIP_TYPE
			,COALESCE(C.TARGET_CD, COALESCE(B.CERT_TYPE, ''))
			,COALESCE(B.CERT_CODE, '') (CS)
			,COALESCE(B.CUST_NAME, '') 
			ORDER BY B.UPDATE_TIME DESC
			) = 1;
ALTER TABLE TEMPDB.T01_PTY_RELA_H_A3 DROP START_DT;